name: Check commit message format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Setup and run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: |
          pip install GitPython
          python .github/workflows/check_commit_message_format.py "${{ steps.extract_branch.outputs.branch }}"